namespace Yak2D
{
    /// <summary>
    /// An interface for framework messages. The default implementation outputs to console (and only for a DEBUG build). The user may define their own to redirect messages generated by the framework
    /// </summary>
    public interface IFrameworkMessenger
    {
        /// <summary>
        /// Called by the framework to report a message
        /// </summary>
        /// <param name="message">The message</param>
        void Report(string message);

        /// <summary>
        /// Called when application is shutting down. Custom user implementations should release non-framework related resources here
        /// </summary>
        void Shutdown();
    }
}