namespace Yak2D
{
    /// <summary>
    /// The Distortion effect is generated by shifting texture coorindates based on the gradient of a height map, scaled by a chosen factor
    /// </summary>
    public struct DistortionEffectConfiguration
    {
        /// <summary>
        /// Scales the internal height map gradient at each pixel to generate the texture coordiante shift
        /// </summary>
        public float DistortionScalar { get; set; }
    }
}